# Generated by Django 3.2.8 on 2021-10-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='to_date',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='duration',
            field=models.CharField(default=5, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='title',
            field=models.CharField(blank=True, max_length=66),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
