# Generated by Django 3.2.8 on 2021-10-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='http://localhost:8000//watch-video/', max_length=90)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes')),
            ],
        ),
    ]
